title: Andre Leitzke
author:
  email: leitzke.andre@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This is just a place where I can formalize some of the things I'm learning.
  Hopefully they may be helpful for someone (most likely: future me).

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: github,          user_url: "https://github.com/leitzke-andre" }
    - { platform: mastodon,        user_url: "https://hachyderm.io/@leitzke" }
    - { platform: mastodon,        user_url: "https://firefish.tech/@leitzke" }
    - { platform: linkedin,        user_url: "https://www.linkedin.com/in/andreleitzke" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
